version: '3.9'

services:
  php:
    # image: php:7.4.19-apache
    build: .
    user: root
    ports:
      - 80:80
      # - 8080:8080
      # - 9000:9000 # xdebug port
      # - 9003:9003 # xdebug port
    volumes:
      - ~/Projects:/var/www/html/