# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: example
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_TCP_PORT: 48897
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - 48897:48897