# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: postgres:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      # MYSQL_TCP_PORT: 48898
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    ports:
      - 48899:5432